### PR TITLE
feat!: upgrade to Capacitor v6

### PR DESCRIPTION
**Pull request by tafelnl**
Just ran `npx @capacitor/plugin-migration-v5-to-v6@latest`

cc @BranchMetrics/saas-sdk-devs for visibility.

### CODE REVIEW

**Comment by marshall86** [comment]
when are you going to complete the migration to capacitor 6?

**Comment by tafelnl** [comment]
@nsingh-branch

**Comment by nsingh-branch** [comment]
@tafelnl @marshall86 Hi, I appreciate the PR and patience. This is on our roadmap and I will try to look into this soon, but can't give an exact date yet.

**Comment by nsingh-branch** [comment]
@tafelnl @marshall86 This has been included in the latest release, 8.0.0.

**Pull request closed without merging**
